#!/bin/sh
#
# Generate build_id.h, the header that tells the firmware which commit it was
# built from. Called by the pre-build step in .cproject.
#
# Usage: build_id.sh <project-root> <output-header>
#
# .version in the project root is tracked and marked export-subst in
# .gitattributes, which is what decides where the id comes from:
#
#   - in a git checkout its placeholder is still unsubstituted, and the commit
#     and the dirty flag are read from git
#   - in a source export git archive has already substituted the commit, and
#     .version is the only source
#
# There is no fallback. A tree that is neither fails the build, rather than
# producing firmware that cannot be traced back to a commit.

set -eu

die() {
	echo "build_id.sh: $*" >&2
	exit 1
}

SRC=$1
OUT=$2

VERSION=$SRC/.version
BUILD_ID_DIRTY=0

[ -r "$VERSION" ] || die "$VERSION is missing"

# Whether git tracks this .version, not merely whether some repository is
# above us: an export unpacked inside an unrelated working tree would
# otherwise be stamped with that tree's commit.
if git -C "$SRC" ls-files --error-unmatch .version >/dev/null 2>&1; then
	BUILD_ID=0x$(git -C "$SRC" log -1 --pretty=format:%H)
	git -C "$SRC" diff --quiet HEAD || BUILD_ID_DIRTY=1
else
	# the template survives only where it was never exported, and $Format has
	# to be matched in the file, since sourcing it would expand the name away
	if grep -q '[$]Format:' "$VERSION"; then
		die "$VERSION still holds the export-subst template, and there is no git to read instead"
	fi
	. "$VERSION"
	case ${BUILD_ID:-} in
	0x*) ;;
	*) die "$VERSION defines no usable BUILD_ID" ;;
	esac
fi

# both sources hand over the full hash; BUILD_ID reaches the SOM as a uint32,
# so keep 0x and the leading eight digits
BUILD_ID=$(printf '%.10s' "$BUILD_ID")

printf '/* generated by tools/build_id.sh, do not modify */\n#define BUILD_ID %s\n' "$BUILD_ID" >"$OUT"
if [ "$BUILD_ID_DIRTY" != 0 ]; then
	printf '#define BUILD_ID_DIRTY 1\n' >>"$OUT"
fi
